// THIS IS AN AUTOGENERATED FILE BY CREATE-WEB3-DAPP

export type CW3DConfig = {
  mainnetName: string;
  mainnetChainId: number;
  testnetChainId: number;
  testnetChainName: string;
};

const config = {
  mainnetName: "shape",
  mainnetChainId: 360,
  testnetChainId: 11011,
  testnetChainName: "shape-sepolia",
} as const satisfies CW3DConfig;

export default config;
